### ISSUE TITLE
ImportError: cannot import name 'AsyncClient' from 'g4f.client'

### ISSUE THREAD

**Issue by kogakisaki** [xtekky/gpt4free#2280]
**Bug description**
Cannot run API after i update g4f to 0.3.3.0, the error show: `ImportError: cannot import name 'AsyncClient' from 'g4f.client' (/opt/render/project/src/.venv/lib/python3.11/site-packages/g4f/client/__init__.py)`

**Step to reproduce**
1. Run `pip install -U g4f`
2. Run `python main.py` (see below)
3. See error

**Environment**
- Python 3.12
- Environment: Render

**Additional context**
Here is my `main.py`

```python
from g4f.api import run_api
import os.path
from g4f.cookies import set_cookies_dir, read_cookie_files

import g4f.debug
g4f.debug.logging = True

cookies_dir = os.path.join(os.path.dirname(__file__), "har_and_cookies")
set_cookies_dir(cookies_dir)
read_cookie_files(cookies_dir)

run_api()
```

**Comment by mgytr** [comment]
I also have this problem. Right now, you can downgrade to 0.3.2.9
```
pip uninstall g4f
pip install g4f==0.3.2.9
```

**Comment by kqlio67** [comment]
@kogakisaki @mgytr

Thank you for reporting this issue. I apologize for the inconvenience caused by the `ImportError` related to `AsyncClient` in version 0.3.3.0 of the `g4f` package.

I submitted a pull request to address this issue, and the maintainers of the package have accepted and merged it. The fix is now available in version 0.3.3.1. You can find the release details here: https://github.com/xtekky/gpt4free/releases/tag/0.3.3.1

To resolve the error, you have a couple of options:

1. Upgrade the package to the latest version:
   ```
   pip install --upgrade g4f
   ```

2. If you prefer to uninstall the current version and then install the latest version, you can do the following:
   ```
   pip uninstall g4f
   pip install g4f
   ```

   Alternatively, you can specify the version explicitly:
   ```
   pip uninstall g4f
   pip install g4f==0.3.3.1
   ```

@kogakisaki I have tested your code sample with the updated version, and I can confirm that it now runs without any errors. However, I recommend testing it in your specific environment to ensure compatibility.

**Comment by AndreySupr** [comment]
I have version 0.3.2.9 and everything works.
updated to the latest, error
 from g4f.client import AsyncClient
 ImportError: Unable to import name 'AsyncClient' from 'g4f.client' (/usr/local/lib/python3>

**Comment by 3rapazoid** [comment]
такая же проблема, но при откате версии провайдера не работают , просят обновить и появляется , почините пожалуйста
