### ISSUE TITLE
3.0.7 provider base class error Bing: TypeError: BaseSession.__init__() got an unexpected keyword argument 'proxy'

### ISSUE THREAD

**Issue by brycepg** [xtekky/gpt4free#1910]
**Bug description**
Upgrade to 3.0.6 from <3.0.0

Execute streaming completion

ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bryce/.cache/pypoetry/virtualenvs/gpt4discord-_1vRy51C-py3.10/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/mnt/c/Users/Bryce/gpt4free-discord/gpt4discord/discord.py", line 239, in on_message
    assistant_content = await stream_llm_response_to_discord(
  File "/mnt/c/Users/Bryce/gpt4free-discord/gpt4discord/discord.py", line 357, in stream_llm_response_to_discord
    for stream_tokens in response:
  File "/home/bryce/.cache/pypoetry/virtualenvs/gpt4discord-_1vRy51C-py3.10/lib/python3.10/site-packages/g4f/providers/retry_provider.py", line 95, in create_completion
    raise_exceptions(exceptions)
  File "/home/bryce/.cache/pypoetry/virtualenvs/gpt4discord-_1vRy51C-py3.10/lib/python3.10/site-packages/g4f/providers/retry_provider.py", line 231, in raise_exceptions
    raise RetryProviderError("RetryProvider failed:\n" + "\n".join([
g4f.errors.RetryProviderError: RetryProvider failed:
Liaobots: ResponseStatusError: Response 401: {"message":"401 Unauthorized"}
Bing: TypeError: BaseSession.__init__() got an unexpected keyword argument 'proxy'

**Screenshots**

**Environment**
Python 3.10.12

USA

**Additional context**
Works fine on <3.0.0

**Comment by jackiezhangcn** [comment]
experience the same issue

**Comment by MikeL1300** [comment]
This issue can be fixed by updating your curl package. For example:

 pip install -U curl-cffi

**Comment by rqi14** [comment]
> This issue can be fixed by updating your curl package. For example:
> 
> pip install -U curl-cffi

Hi. Do you know how to fix this in the docker image version?

**Comment by hlohaus** [comment]
You have to execute:

`docker pull <image-name>`

**Comment by hlohaus** [comment]
The minimum version of curl_cffi is 6.2 in g4f.
